hook global InsertChar \t %{ try %{
      execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}
hook global InsertDelete ' ' %{ try %{
      execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}
set-option global indentwidth 2

source "%val{config}/thirdparty/fzf.kak/rc/fzf.kak"
source "%val{config}/thirdparty/fzf.kak/rc/modules/fzf-file.kak"
source "%val{config}/thirdparty/fzf.kak/rc/modules/fzf-buffer.kak"
source "%val{config}/thirdparty/fzf.kak/rc/modules/fzf-search.kak"
source "%val{config}/thirdparty/fzf.kak/rc/modules/fzf-cd.kak"
map global normal <c-p> ': fzf-mode<ret>'

hook global BufCreate .*[.](pyi) %{
  set-option buffer filetype python
}
