#!/usr/bin/env nix-shell
#!nix-shell -i bash -p subversion nix-prefetch-scripts

set -o errexit -o pipefail -o nounset

self=$(basename $0)

function register_source() {
  relpath=$(realpath --relative-to=$checkout_dir $PWD)
  url=$(svn info | grep -E '^URL: ' | cut -d ' ' -f 2)
  rev=$(svn info | grep -E '^Revision: ' | cut -d ' ' -f 2)
  echo >&2 "Found external $url at $relpath; locking at revision r$rev"
  sha256=$(nix-prefetch-svn $url $rev | tail -1)
  cat <<EOF
  "$relpath" = fetchsvn {
    url = "$url";
    rev = "$rev";
    sha256 = "$sha256";
    ignoreExternals = true;
  };
EOF
}

top_url="svn://repo.hu/pcb-rnd/trunk"

working_dir=$TEMP/pcb-rnd-gen-sources
mkdir -p $working_dir
rm -rf $working_dir/*

checkout_dir=$working_dir/checkout
echo >&2 "Checking out pcb-rnd into $checkout_dir"
svn co --quiet "$top_url" "$checkout_dir"

echo '# This file is autogenerated by '$self'.'
echo '# Do not edit manually!'
echo '#'
echo '# Instead, run:'
echo '#   ./'$self' > THIS_FILE'
echo

echo '{ fetchsvn }:'
echo
echo '{'
for svn_dir in $(find $checkout_dir -name .svn -type d); do
  cd $(dirname $svn_dir)
  register_source
done
echo '}'

echo >&2 "Cleaning up $working_dir"
rm -rf $working_dir
