# This file is autogenerated by gen-svn-sources.sh.
# Do not edit manually!
#
# Instead, run:
#   ./gen-svn-sources.sh > THIS_FILE

{ fetchsvn }:

{
  "src_3rd/libuundo" = fetchsvn {
    url = "svn://repo.hu/libuundo/trunk/libuundo";
    rev = "70";
    sha256 = "1c99939v2hxmc1sdxy2p89ikg5c230an9x618cqr5v43yxdn6prc";
    ignoreExternals = true;
  };
  "src_3rd/libminuid" = fetchsvn {
    url = "svn://repo.hu/libminuid/trunk/libminuid";
    rev = "30";
    sha256 = "02mjm3lb2wq1bac5d5x0p5fcp6izch4z09q39mljxyr9f66glf7p";
    ignoreExternals = true;
  };
  "src_3rd/puplug" = fetchsvn {
    url = "svn://repo.hu/puplug/trunk/puplug";
    rev = "255";
    sha256 = "0b01w37m4ry1bkci94bmkyxh63srygbniiyp1xd2rcly8s9ziii1";
    ignoreExternals = true;
  };
  "src_3rd/gensexpr" = fetchsvn {
    url = "svn://repo.hu/gensexpr/trunk/gensexpr";
    rev = "64";
    sha256 = "0waay7msf6ai46fwakqw8x73xn0zwxf26hk2ab518iphad0cvfzh";
    ignoreExternals = true;
  };
  "src_3rd/sphash" = fetchsvn {
    url = "svn://repo.hu/sphash/trunk";
    rev = "61";
    sha256 = "19fvwlyl2m83bkdskmb4gp5bdhz603ya9vqc06pczbbn5r8jilwx";
    ignoreExternals = true;
  };
  "src_3rd/genregex" = fetchsvn {
    url = "svn://repo.hu/genregex/trunk/src";
    rev = "97";
    sha256 = "0s8s0wllz9nx5ips7vzyjzcmw59k8rxhw57gpxwqziflm8i48x2r";
    ignoreExternals = true;
  };
  "src_3rd/liblhtpers" = fetchsvn {
    url = "svn://repo.hu/lihata/trunk/src/liblhtpers";
    rev = "1222";
    sha256 = "1m49y5s91fgq21inmdd8g07gxsiwnjsvw7cl31b63d1rhgyfavh8";
    ignoreExternals = true;
  };
  "src_3rd/liblihata" = fetchsvn {
    url = "svn://repo.hu/lihata/trunk/src/liblihata";
    rev = "1222";
    sha256 = "11y3zkqmzlhjcwn68kzryy2xgcc3j5ycxswcnd4fq8cx27lvdjvi";
    ignoreExternals = true;
  };
  "src_3rd/genvector" = fetchsvn {
    url = "svn://repo.hu/genvector/trunk/genvector";
    rev = "174";
    sha256 = "0zs6x9x69vzf32cb5wx8p9kbrw2vy2cam1b4k9vcpr000yffvjz1";
    ignoreExternals = true;
  };
  "src_3rd/genlist" = fetchsvn {
    url = "svn://repo.hu/genlist/trunk/genlist";
    rev = "88";
    sha256 = "1y15kksqmvj1likkgaippsz3lckdq1f5241immwj80qyblg10l2b";
    ignoreExternals = true;
  };
  "src_3rd/genht" = fetchsvn {
    url = "svn://repo.hu/genht/trunk/src";
    rev = "83";
    sha256 = "1ikf8anwgr5bxmnm177ls2clb5cy2j7kdjirmfncs065k2nv0byz";
    ignoreExternals = true;
  };
  "scconfig/src" = fetchsvn {
    url = "svn://repo.hu/scconfig/trunk/src";
    rev = "1217";
    sha256 = "0rhc8ng3icmgdb775y84hai73lxl5y4vfd32p2mv25waspcsx6xf";
    ignoreExternals = true;
  };
  "." = fetchsvn {
    url = "svn://repo.hu/pcb-rnd/trunk";
    rev = "13570";
    sha256 = "0rq5x94m6bampq7wcradnhq9m97ff2icjvg85577dq8ha90f8s4c";
    ignoreExternals = true;
  };
}
