# This file has been generated by node2nix 1.6.0. Do not edit!

{ stdenv, python2, utillinux, runCommand, writeTextFile, fetchurl, fetchgit, fetchFromGitHub, nodejs }:

let
  nodeEnv = import ./node-env.nix {
    inherit stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
    libtool = null;
  };
in
(import ./node-packages.nix {
  inherit fetchurl fetchgit fetchFromGitHub;
  inherit nodeEnv;
}).package
