#!/bin/sh

total=$(grep MemTotal /proc/meminfo | tr -dc '[:digit:]')
avail=$(grep MemAvailable /proc/meminfo | tr -dc '[:digit:]')

used_perc=$(echo "(($total-$avail)*100)/$total" | bc)

if [ $used_perc -ge 90 ]; then
  color='#FF0000'
elif [ $used_perc -ge 50 ]; then
  color='#FFA500'
else
  color='#FFFF00'
fi

echo "mem: $used_perc%"
echo "M: $used_perc%"
echo $color
