apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore-transmission-state
  namespace: personal
spec:
  repository:
    name: personal-transmission-state-b2
    namespace: stash
  target:
    rules:
    - paths: [/stash-data]
    replicas: 1
    volumeMounts:
    - name: state-transmission
      mountPath: /stash-data
    volumeClaimTemplates:
    - metadata:
        name: state-transmission-${POD_ORDINAL}
      spec:
        accessModes: [ReadWriteMany]
        resources:
          requests:
            storage: 100Mi
        storageClassName: ceph-fs-gp0
