apiVersion: batch/v1
kind: Job
metadata:
  name: torrent-fs-sync
  namespace: personal
  labels:
    app: torrent-fs-sync
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: torrent-fs-sync
    spec:
      nodeName: maryam
      restartPolicy: Never
      priorityClassName: best-effort
      volumes:
      - name: src
        persistentVolumeClaim:
          claimName: torrent-downloads
      - name: dest
        persistentVolumeClaim:
          claimName: torrent-downloads1
      containers:
      - name: main
        image: eeacms/rsync
        command: [rsync, -av, --numeric-ids, /src/, /dest/]
        volumeMounts:
        - name: src
          mountPath: /src
          readOnly: true
        - name: dest
          mountPath: /dest
          readOnly: false
